/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.mangement.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author admin
 */
public class Department_details extends javax.swing.JFrame {

    /**
     * Creates new form Department_details
     */
    public Department_details() {
        initComponents();
        DisplayTable();
    }
    private void DisplayTable(){
     try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
         String sql="select * from department_details";
         PreparedStatement pstmt=con.prepareStatement(sql);
         ResultSet rs=pstmt.executeQuery();
         t1.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        Dno = new javax.swing.JLabel();
        Dname = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        dno = new javax.swing.JTextField();
        dname = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        img.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\department1.jpg")); // NOI18N
        img.setText("jLabel2");
        jPanel1.add(img);
        img.setBounds(110, 280, 510, 240);

        msg.setBackground(new java.awt.Color(255, 255, 255));
        msg.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 0, 0));
        msg.setText("DEPARTMENT DETAILS");
        jPanel1.add(msg);
        msg.setBounds(1180, 250, 440, 32);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setForeground(new java.awt.Color(0, 0, 0));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(872, 300, 870, 350);

        Dno.setBackground(new java.awt.Color(255, 255, 255));
        Dno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dno.setForeground(new java.awt.Color(0, 0, 0));
        Dno.setText("DEPARTMENT NO");
        jPanel1.add(Dno);
        Dno.setBounds(80, 680, 206, 40);

        Dname.setBackground(new java.awt.Color(255, 255, 255));
        Dname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dname.setForeground(new java.awt.Color(0, 0, 0));
        Dname.setText("DEPARTMENT NAME");
        jPanel1.add(Dname);
        Dname.setBounds(60, 790, 241, 40);

        Description.setBackground(new java.awt.Color(255, 255, 255));
        Description.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Description.setForeground(new java.awt.Color(0, 0, 0));
        Description.setText("DESCRIPTION");
        jPanel1.add(Description);
        Description.setBounds(120, 890, 157, 40);

        dno.setBackground(new java.awt.Color(0, 0, 0));
        dno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dno);
        dno.setBounds(430, 690, 250, 29);

        dname.setBackground(new java.awt.Color(0, 0, 0));
        dname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dname);
        dname.setBounds(430, 790, 250, 29);

        description.setBackground(new java.awt.Color(0, 0, 0));
        description.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(description);
        description.setBounds(430, 890, 260, 29);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(880, 750, 150, 80);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(1250, 750, 150, 80);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 0));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(1590, 750, 150, 80);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(1260, 900, 150, 80);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\PREVIOUS.jpg")); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 10, 100, 29);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("To delete enter depatment no");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1230, 700, 187, 21);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("To update enter depatment no and update the rest");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1500, 700, 320, 21);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\BG NEW.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1090);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="insert into department_details values(?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,dno.getText());
            ps.setString(2,dname.getText());
            ps.setString(3,description.getText());
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY ADDED DEPARTMENT");
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="delete from department_details where DNO = ?";
            PreparedStatement pstmt=con.prepareStatement(sql);
            pstmt.setInt(1,Integer.parseInt(dno.getText()));
            pstmt.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null, "RECORD DELETED SUCCESSFULLY");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="update department_details set DNAME=?,DESCRIPTION=? where DNO=?";
            PreparedStatement ps=con.prepareStatement(sql);
            
            ps.setString(1,dname.getText());
            ps.setString(2, description.getText());
            ps.setString(3,dno.getText());
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY UPDATED DEPARTMENT");
            con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        dno.setText(null);
        description.setText(" ");
        dname.setText(" ");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Admin_Panel ap=new Admin_Panel();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Dname;
    private javax.swing.JLabel Dno;
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField description;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField dno;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg;
    private javax.swing.JTable t1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
