/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.mangement.system;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.*;
import javax.swing.table.*;
/**
 *
 * @author admin
 */
public class Doctor_details extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_details
     */
    public Doctor_details() {
        initComponents();
        DisplayTable();
    }
     private void DisplayTable(){
     try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
         String sql="select * from register";
         PreparedStatement pstmt=con.prepareStatement(sql);
         ResultSet rs=pstmt.executeQuery();
         t1.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        regl = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        departmentl = new javax.swing.JLabel();
        passwordl = new javax.swing.JLabel();
        emaill = new javax.swing.JLabel();
        phoenl = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        RegId = new javax.swing.JTextField();
        Department = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PhoneNo = new javax.swing.JTextField();
        Pass1 = new javax.swing.JPasswordField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        delete = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1170, 310, 710, 210);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("REGISTERED DOCTOR'S DETAILS");
        jPanel1.add(title);
        title.setBounds(1320, 260, 410, 29);

        namel.setBackground(new java.awt.Color(255, 255, 255));
        namel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namel.setForeground(new java.awt.Color(0, 0, 0));
        namel.setText("NAME");
        jPanel1.add(namel);
        namel.setBounds(240, 330, 60, 22);

        regl.setBackground(new java.awt.Color(255, 255, 255));
        regl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regl.setForeground(new java.awt.Color(0, 0, 0));
        regl.setText("REG ID");
        jPanel1.add(regl);
        regl.setBounds(230, 280, 70, 20);

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setText("GENDER");
        jPanel1.add(gender);
        gender.setBounds(220, 380, 80, 22);

        departmentl.setBackground(new java.awt.Color(255, 255, 255));
        departmentl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        departmentl.setForeground(new java.awt.Color(0, 0, 0));
        departmentl.setText("DEPARTMENT");
        jPanel1.add(departmentl);
        departmentl.setBounds(180, 430, 125, 22);

        passwordl.setBackground(new java.awt.Color(255, 255, 255));
        passwordl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordl.setForeground(new java.awt.Color(0, 0, 0));
        passwordl.setText("PASSWORD");
        jPanel1.add(passwordl);
        passwordl.setBounds(200, 480, 110, 22);

        emaill.setBackground(new java.awt.Color(255, 255, 255));
        emaill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emaill.setForeground(new java.awt.Color(0, 0, 0));
        emaill.setText("E-MAIL");
        jPanel1.add(emaill);
        emaill.setBounds(230, 530, 70, 22);

        phoenl.setBackground(new java.awt.Color(255, 255, 255));
        phoenl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoenl.setForeground(new java.awt.Color(0, 0, 0));
        phoenl.setText("MOBILE NO");
        jPanel1.add(phoenl);
        phoenl.setBounds(200, 580, 110, 22);
        jPanel1.add(Name);
        Name.setBounds(420, 330, 260, 29);
        jPanel1.add(RegId);
        RegId.setBounds(420, 270, 260, 29);
        jPanel1.add(Department);
        Department.setBounds(420, 430, 260, 29);

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email);
        Email.setBounds(420, 530, 260, 29);

        PhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoActionPerformed(evt);
            }
        });
        jPanel1.add(PhoneNo);
        PhoneNo.setBounds(420, 580, 260, 29);

        Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(Pass1);
        Pass1.setBounds(420, 480, 260, 29);

        male.setForeground(new java.awt.Color(0, 0, 0));
        male.setText("MALE");
        jPanel1.add(male);
        male.setBounds(420, 380, 70, 27);

        female.setForeground(new java.awt.Color(0, 0, 0));
        female.setText("FEMALE");
        jPanel1.add(female);
        female.setBounds(500, 380, 90, 27);

        others.setForeground(new java.awt.Color(0, 0, 0));
        others.setText("OTHERS");
        jPanel1.add(others);
        others.setBounds(590, 380, 90, 27);

        delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\delete_final.jpg")); // NOI18N
        delete.setText("jLabel1");
        jPanel1.add(delete);
        delete.setBounds(830, 690, 270, 240);

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\add.jpg")); // NOI18N
        add.setText("jLabel1");
        jPanel1.add(add);
        add.setBounds(160, 700, 270, 245);

        update.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\update.jpg")); // NOI18N
        update.setText("jLabel1");
        jPanel1.add(update);
        update.setBounds(1440, 700, 270, 220);

        Add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Add.setText("ADD DOCTOR");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(160, 950, 270, 40);

        Remove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Remove.setText("REMOVE DOCTOR");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(Remove);
        Remove.setBounds(830, 940, 270, 40);

        Update.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Update.setText("UPDATE DOCTOR");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(1440, 930, 270, 40);

        msg.setBackground(new java.awt.Color(255, 255, 255));
        msg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 0, 0));
        msg.setText("for deletion give only ID");
        jPanel1.add(msg);
        msg.setBounds(860, 650, 230, 21);

        msg1.setBackground(new java.awt.Color(255, 255, 255));
        msg1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        msg1.setForeground(new java.awt.Color(0, 0, 0));
        msg1.setText("for updation give only ID and change the rest");
        jPanel1.add(msg1);
        msg1.setBounds(1390, 660, 390, 21);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 640, 111, 40);

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\PREVIOUS.jpg")); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 10, 100, 29);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\BG NEW.jpg")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, -50, 1940, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoActionPerformed

    private void Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass1ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
 try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="insert into register values(?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,RegId.getText());
            ps.setString(2,Name.getText());
            String dept="";
            if(male.isSelected()){
                dept=male.getText();
            }
            if(female.isSelected()){
                dept=female.getText();
            }
            if(others.isSelected()){
                dept=others.getText();
            }
            ps.setString(3, dept);
            ps.setString(4,Department.getText());
            ps.setString(5,Pass1.getText());
            ps.setString(6,Email.getText());
            ps.setString(7,PhoneNo.getText());
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY ADDED DOCTOR");
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
                                                 // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="delete from register where NO = ?";
            PreparedStatement pstmt=con.prepareStatement(sql);
            pstmt.setInt(1,Integer.parseInt(RegId.getText()));
            pstmt.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null, "RECORD DELETED SUCCESSFULLY");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="update register set NAME=?,GENDER=?,DEPARTMENT=?,PASSWORD=?,EMAIL=?,PHONENUMBER=? where NO=?";
            PreparedStatement ps=con.prepareStatement(sql);
            
            ps.setString(1,Name.getText());
            String dept="";
            if(male.isSelected()){
                dept=male.getText();
            }
            if(female.isSelected()){
                dept=female.getText();
            }
            if(others.isSelected()){
                dept=others.getText();
            }
            ps.setString(2, dept);
            ps.setString(3,Department.getText());
            ps.setString(4,Pass1.getText());
            ps.setString(5,Email.getText());
            ps.setString(6,PhoneNo.getText());
            ps.setString(7, RegId.getText());
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)t1.getModel ();
            model.setRowCount(0);
            DisplayTable();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY UPDATED DOCTOR");
            con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RegId.setText(null);
        Name.setText(" ");
        male.setSelected(false);
        female.setSelected(false);
        others.setSelected(false);
        Department.setText(" ");
        Email.setText(" ");
        PhoneNo.setText(" ");
        Pass1.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Admin_Panel ap=new Admin_Panel();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_details().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Department;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField RegId;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Update;
    private javax.swing.JLabel add;
    private javax.swing.JButton back;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel departmentl;
    private javax.swing.JLabel emaill;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel namel;
    private javax.swing.JRadioButton others;
    private javax.swing.JLabel passwordl;
    private javax.swing.JLabel phoenl;
    private javax.swing.JLabel regl;
    private javax.swing.JTable t1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
