/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.mangement.system;

/**
 *
 * @author sakshi budhia
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admini = new javax.swing.JLabel();
        adminb = new javax.swing.JButton();
        receptionist = new javax.swing.JLabel();
        recepb = new javax.swing.JButton();
        doctor = new javax.swing.JLabel();
        pharmacyi = new javax.swing.JLabel();
        doctorb = new javax.swing.JButton();
        pharmacistsb = new javax.swing.JButton();
        patienti = new javax.swing.JLabel();
        patientl = new javax.swing.JButton();
        backgroung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 1080));
        jPanel1.setLayout(null);

        admini.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\admin_final.png")); // NOI18N
        admini.setText("ADMIN");
        jPanel1.add(admini);
        admini.setBounds(130, 600, 200, 180);

        adminb.setBackground(new java.awt.Color(0, 0, 0));
        adminb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminb.setForeground(new java.awt.Color(255, 255, 255));
        adminb.setText("ADMIN");
        adminb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbActionPerformed(evt);
            }
        });
        jPanel1.add(adminb);
        adminb.setBounds(160, 830, 120, 30);

        receptionist.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\receptionist_final.png")); // NOI18N
        jPanel1.add(receptionist);
        receptionist.setBounds(490, 600, 200, 180);

        recepb.setBackground(new java.awt.Color(0, 0, 0));
        recepb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recepb.setForeground(new java.awt.Color(255, 255, 255));
        recepb.setText("RECEPTIONIST");
        recepb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepbActionPerformed(evt);
            }
        });
        jPanel1.add(recepb);
        recepb.setBounds(500, 830, 176, 30);

        doctor.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\doctor_final.png")); // NOI18N
        doctor.setText("jLabel1");
        jPanel1.add(doctor);
        doctor.setBounds(830, 600, 200, 180);

        pharmacyi.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\pharmacist_final.png")); // NOI18N
        pharmacyi.setText("jLabel1");
        jPanel1.add(pharmacyi);
        pharmacyi.setBounds(1190, 600, 200, 180);

        doctorb.setBackground(new java.awt.Color(0, 0, 0));
        doctorb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doctorb.setForeground(new java.awt.Color(255, 255, 255));
        doctorb.setText("DOCTOR");
        doctorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbActionPerformed(evt);
            }
        });
        jPanel1.add(doctorb);
        doctorb.setBounds(880, 830, 116, 30);

        pharmacistsb.setBackground(new java.awt.Color(0, 0, 0));
        pharmacistsb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pharmacistsb.setForeground(new java.awt.Color(255, 255, 255));
        pharmacistsb.setText("PHARMACIST");
        pharmacistsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistsbActionPerformed(evt);
            }
        });
        jPanel1.add(pharmacistsb);
        pharmacistsb.setBounds(1210, 830, 160, 30);

        patienti.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\patient icon.png")); // NOI18N
        jPanel1.add(patienti);
        patienti.setBounds(1530, 600, 200, 180);

        patientl.setBackground(new java.awt.Color(0, 0, 0));
        patientl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientl.setForeground(new java.awt.Color(255, 255, 255));
        patientl.setText("PATIENT");
        patientl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientlActionPerformed(evt);
            }
        });
        jPanel1.add(patientl);
        patientl.setBounds(1560, 830, 160, 30);

        backgroung.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\LOGIN_BACK_FINAL.jpg")); // NOI18N
        backgroung.setText("LOGIN");
        jPanel1.add(backgroung);
        backgroung.setBounds(0, -80, 1900, 1240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbActionPerformed
Admin_login al=new Admin_login();
al.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_adminbActionPerformed

    private void recepbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepbActionPerformed
ReceptionistLogin al=new ReceptionistLogin();
al.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_recepbActionPerformed

    private void doctorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbActionPerformed
Doctor_login al=new Doctor_login();
al.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_doctorbActionPerformed

    private void pharmacistsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistsbActionPerformed
Pharmacist_login al=new Pharmacist_login();
al.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacistsbActionPerformed

    private void patientlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientlActionPerformed
        // TODO add your handling code here:
        patient_login al=new patient_login();
        al.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_patientlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminb;
    private javax.swing.JLabel admini;
    private javax.swing.JLabel backgroung;
    private javax.swing.JLabel doctor;
    private javax.swing.JButton doctorb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patienti;
    private javax.swing.JButton patientl;
    private javax.swing.JButton pharmacistsb;
    private javax.swing.JLabel pharmacyi;
    private javax.swing.JButton recepb;
    private javax.swing.JLabel receptionist;
    // End of variables declaration//GEN-END:variables
}
