/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.mangement.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class patient_register extends javax.swing.JFrame {

    /**
     * Creates new form patient_register
     */
    public patient_register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        REGID = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        AGE = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        ISSUE = new javax.swing.JLabel();
        PHONENO = new javax.swing.JLabel();
        PASSWORD1 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JLabel();
        regid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        issue = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        pass1 = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTER AS PATIENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(730, 220, 380, 48);

        REGID.setBackground(new java.awt.Color(255, 255, 255));
        REGID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        REGID.setForeground(new java.awt.Color(0, 0, 0));
        REGID.setText("REG ID");
        jPanel1.add(REGID);
        REGID.setBounds(390, 320, 59, 25);

        NAME.setBackground(new java.awt.Color(255, 255, 255));
        NAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NAME.setForeground(new java.awt.Color(0, 0, 0));
        NAME.setText("NAME");
        jPanel1.add(NAME);
        NAME.setBounds(400, 370, 54, 25);

        AGE.setBackground(new java.awt.Color(255, 255, 255));
        AGE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AGE.setForeground(new java.awt.Color(0, 0, 0));
        AGE.setText("AGE");
        jPanel1.add(AGE);
        AGE.setBounds(420, 410, 36, 25);

        GENDER.setBackground(new java.awt.Color(255, 255, 255));
        GENDER.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GENDER.setForeground(new java.awt.Color(0, 0, 0));
        GENDER.setText("GENDER");
        jPanel1.add(GENDER);
        GENDER.setBounds(390, 460, 72, 25);

        ISSUE.setBackground(new java.awt.Color(255, 255, 255));
        ISSUE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ISSUE.setForeground(new java.awt.Color(0, 0, 0));
        ISSUE.setText("ISSUE");
        jPanel1.add(ISSUE);
        ISSUE.setBounds(410, 510, 49, 25);

        PHONENO.setBackground(new java.awt.Color(255, 255, 255));
        PHONENO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PHONENO.setForeground(new java.awt.Color(0, 0, 0));
        PHONENO.setText("PHONE NO");
        jPanel1.add(PHONENO);
        PHONENO.setBounds(370, 560, 96, 25);

        PASSWORD1.setBackground(new java.awt.Color(255, 255, 255));
        PASSWORD1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PASSWORD1.setForeground(new java.awt.Color(0, 0, 0));
        PASSWORD1.setText("CONFIRM PASSWORD");
        jPanel1.add(PASSWORD1);
        PASSWORD1.setBounds(290, 670, 189, 25);

        PASSWORD.setBackground(new java.awt.Color(255, 255, 255));
        PASSWORD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(0, 0, 0));
        PASSWORD.setText("PASSWORD");
        jPanel1.add(PASSWORD);
        PASSWORD.setBounds(370, 610, 101, 25);

        regid.setBackground(new java.awt.Color(0, 0, 0));
        regid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(regid);
        regid.setBounds(600, 310, 270, 29);

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name);
        name.setBounds(600, 360, 270, 29);

        age.setBackground(new java.awt.Color(0, 0, 0));
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age);
        age.setBounds(600, 410, 270, 29);

        issue.setBackground(new java.awt.Color(0, 0, 0));
        issue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(issue);
        issue.setBounds(600, 510, 270, 29);

        phoneno.setBackground(new java.awt.Color(0, 0, 0));
        phoneno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(phoneno);
        phoneno.setBounds(600, 560, 270, 29);

        male.setBackground(new java.awt.Color(0, 0, 0));
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("MALE");
        jPanel1.add(male);
        male.setBounds(600, 460, 68, 27);

        female.setBackground(new java.awt.Color(0, 0, 0));
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("FEMALE");
        jPanel1.add(female);
        female.setBounds(680, 460, 83, 27);

        others.setBackground(new java.awt.Color(0, 0, 0));
        others.setForeground(new java.awt.Color(255, 255, 255));
        others.setText("OTHERS");
        jPanel1.add(others);
        others.setBounds(780, 460, 85, 27);

        pass1.setBackground(new java.awt.Color(0, 0, 0));
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pass1);
        pass1.setBounds(600, 610, 270, 29);

        pass2.setBackground(new java.awt.Color(0, 0, 0));
        pass2.setForeground(new java.awt.Color(255, 255, 255));
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass2FocusLost(evt);
            }
        });
        jPanel1.add(pass2);
        pass2.setBounds(600, 670, 270, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1230, 390, 200, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\BG NEW.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1090);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="insert into patient_details values(?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,regid.getText());
            ps.setString(2,name.getText());
            String dept="";
            if(male.isSelected()){
                dept=male.getText();
            }
            if(female.isSelected()){
                dept=female.getText();
            }
            if(others.isSelected()){
                dept=others.getText();
            }
            ps.setString(4, dept);
            ps.setString(3,age.getText());
            ps.setString(5,issue.getText());
            ps.setString(6,phoneno.getText());
            ps.setString(7,pass1.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY REGISTERED.YOU CAN NOW LOGIN");
            patient_login al=new patient_login();
            al.setVisible(true);
            this.dispose();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void validatePassword(){
        String pwd1=pass1.getText();
        String pwd2=pass2.getText();
        if(!pwd1.equals(pwd2)){
        JOptionPane.showMessageDialog(this,"the password does not match,please check");
        }
    }
    private void pass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusLost
        // TODO add your handling code here:
        validatePassword();
    }//GEN-LAST:event_pass2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGE;
    private javax.swing.JLabel GENDER;
    private javax.swing.JLabel ISSUE;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JLabel PASSWORD1;
    private javax.swing.JLabel PHONENO;
    private javax.swing.JLabel REGID;
    private javax.swing.JTextField age;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField issue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton others;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField regid;
    // End of variables declaration//GEN-END:variables
}
