/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.mangement.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Receptionist_register extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist_register
     */
    public Receptionist_register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Regno = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        RegNo = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PhoneNo = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        pass1 = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTER AS RECEPTIONIST");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 250, 500, 70);

        Regno.setBackground(new java.awt.Color(255, 255, 255));
        Regno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Regno.setForeground(new java.awt.Color(0, 0, 0));
        Regno.setText("REGISTRATION NUMBER");
        jPanel1.add(Regno);
        Regno.setBounds(380, 360, 283, 32);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText(" NAME");
        jPanel1.add(name);
        name.setBounds(580, 430, 79, 32);

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setText("GENDER");
        jPanel1.add(gender);
        gender.setBounds(580, 560, 96, 32);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("PASSWORD");
        jPanel1.add(password);
        password.setBounds(550, 690, 134, 32);

        password1.setBackground(new java.awt.Color(255, 255, 255));
        password1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        password1.setForeground(new java.awt.Color(0, 0, 0));
        password1.setText("CONFIRM PASSWORD");
        jPanel1.add(password1);
        password1.setBounds(450, 760, 252, 32);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setText("EMAIL");
        jPanel1.add(email);
        email.setBounds(590, 490, 73, 32);

        phoneno.setBackground(new java.awt.Color(255, 255, 255));
        phoneno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        phoneno.setForeground(new java.awt.Color(0, 0, 0));
        phoneno.setText("PHONE NUMBER");
        jPanel1.add(phoneno);
        phoneno.setBounds(490, 620, 193, 32);

        RegNo.setBackground(new java.awt.Color(0, 0, 0));
        RegNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(RegNo);
        RegNo.setBounds(880, 370, 290, 29);

        Name.setBackground(new java.awt.Color(0, 0, 0));
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name);
        Name.setBounds(880, 430, 290, 29);

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Email);
        Email.setBounds(880, 490, 290, 29);

        PhoneNo.setBackground(new java.awt.Color(0, 0, 0));
        PhoneNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PhoneNo);
        PhoneNo.setBounds(880, 620, 290, 29);

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setForeground(new java.awt.Color(0, 0, 0));
        male.setText("MALE");
        jPanel1.add(male);
        male.setBounds(880, 560, 68, 27);

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setForeground(new java.awt.Color(0, 0, 0));
        female.setText("FEMALE");
        jPanel1.add(female);
        female.setBounds(980, 560, 83, 27);

        others.setBackground(new java.awt.Color(255, 255, 255));
        others.setForeground(new java.awt.Color(0, 0, 0));
        others.setText("OTHERS");
        jPanel1.add(others);
        others.setBounds(1090, 560, 85, 27);

        pass1.setBackground(new java.awt.Color(0, 0, 0));
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        jPanel1.add(pass1);
        pass1.setBounds(880, 690, 290, 29);

        pass2.setBackground(new java.awt.Color(0, 0, 0));
        pass2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pass2);
        pass2.setBounds(880, 770, 290, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 870, 122, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\images\\BG NEW.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 0, 2080, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/doctor_register","root","sakshi.budhia");
            String sql="insert into receptionist_details values(?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,RegNo.getText());
            ps.setString(2,Name.getText());
            String dept="";
            if(male.isSelected()){
                dept=male.getText();
            }
            if(female.isSelected()){
                dept=female.getText();
            }
            if(others.isSelected()){
                dept=others.getText();
            }
            ps.setString(3, dept);
            ps.setString(4,pass1.getText());
            ps.setString(5,Email.getText());
            ps.setString(6,PhoneNo.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"SUCCESFULLY REGISTERED.YOU CAN NOW LOGIN");
            ReceptionistLogin al=new ReceptionistLogin();
            al.setVisible(true);
            this.dispose();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
        // TODO add your handling code here:
        validatePassword();
    }//GEN-LAST:event_pass1FocusLost
    public void validatePassword(){
        String pwd1=pass1.getText();
        String pwd2=pass2.getText();
        if(!pwd1.equals(pwd2)){
        JOptionPane.showMessageDialog(this,"the password does not match,please check");
        }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField RegNo;
    private javax.swing.JLabel Regno;
    private javax.swing.JLabel email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel name;
    private javax.swing.JRadioButton others;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel phoneno;
    // End of variables declaration//GEN-END:variables
}
